package com.forge.app.data.repo

import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import com.forge.app.data.db.dao.LoggedExerciseDao
import com.forge.app.data.db.dao.LoggedSetDao
import com.forge.app.data.db.dao.SessionDao
import com.forge.app.program.Program
import dagger.hilt.android.qualifiers.ApplicationContext
import java.io.File
import java.time.Instant
import java.time.ZoneId
import java.time.format.DateTimeFormatter
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Generates a single-page PDF for a session (#149).
 * Uses Android's built-in PdfDocument — no external dependencies.
 */
@Singleton
class PdfExportRepository @Inject constructor(
    @ApplicationContext private val context: Context,
    private val sessionDao: SessionDao,
    private val loggedExerciseDao: LoggedExerciseDao,
    private val loggedSetDao: LoggedSetDao
) {
    private val zone = ZoneId.systemDefault()
    private val dateFmt = DateTimeFormatter.ofPattern("MMMM d, yyyy")
    private val timeFmt = DateTimeFormatter.ofPattern("h:mm a")

    suspend fun exportLastSessionPdf(): File? {
        val lastSession = sessionDao.allFinished().lastOrNull() ?: return null
        return exportSessionPdf(lastSession.id)
    }

    suspend fun exportSessionPdf(sessionId: Long): File? {
        val session = sessionDao.get(sessionId) ?: return null
        val exercises = loggedExerciseDao.forSession(sessionId)
        val dayName = Program.days.firstOrNull { it.key == session.dayKey }?.defaultName
            ?: session.dayKey
        val dateStr = Instant.ofEpochMilli(session.startedAt).atZone(zone).format(dateFmt)
        val timeStr = Instant.ofEpochMilli(session.startedAt).atZone(zone).format(timeFmt)
        val durationMin = session.finishedAt?.let { ((it - session.startedAt) / 60_000).toInt() }

        val doc = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create() // A4
        val page = doc.startPage(pageInfo)
        val canvas: Canvas = page.canvas

        val titlePaint = Paint().apply { textSize = 24f; color = Color.BLACK; isFakeBoldText = true }
        val headerPaint = Paint().apply { textSize = 14f; color = Color.BLACK; isFakeBoldText = true }
        val bodyPaint = Paint().apply { textSize = 11f; color = Color.DKGRAY }
        val mutedPaint = Paint().apply { textSize = 10f; color = Color.GRAY }
        val linePaint = Paint().apply { color = Color.LTGRAY; strokeWidth = 1f }

        var y = 60f
        val margin = 50f

        // Header
        canvas.drawText("FORGE — Session Report", margin, y, titlePaint)
        y += 30f
        canvas.drawText("$dayName · $dateStr · $timeStr", margin, y, bodyPaint)
        y += 16f
        if (durationMin != null) {
            canvas.drawText("Duration: ${durationMin}m  ·  Volume: ${(session.totalVolumeLb ?: 0.0).toInt()} lb  ·  PRs: ${session.prCount}", margin, y, bodyPaint)
            y += 16f
        }

        canvas.drawLine(margin, y + 4, 595 - margin, y + 4, linePaint)
        y += 20f

        // Exercise sections
        for (ex in exercises) {
            if (y > 780f) break // safety: don't overflow page
            val sets = loggedSetDao.forLoggedExercise(ex.id)
            val exName = ex.swappedName ?: Program.exercise(ex.exerciseId)?.name ?: ex.exerciseId
            canvas.drawText(exName, margin, y, headerPaint)
            y += 16f
            sets.forEachIndexed { i, set ->
                canvas.drawText("  Set ${i + 1}: ${set.weightText} × ${set.reps}", margin + 8, y, bodyPaint)
                y += 13f
            }
            y += 6f
        }

        // Footer
        canvas.drawText("Generated by Forge · ${System.currentTimeMillis()}", margin, 820f, mutedPaint)

        doc.finishPage(page)
        val file = File(context.filesDir, "forge_session_${sessionId}.pdf")
        file.outputStream().use { doc.writeTo(it) }
        doc.close()
        return file
    }
}
